p1: p1.awk
	clear
	gawk -f p1.awk < harrypotter2

p2: p2.awk
	clear
	gawk -f p2.awk < harrypotter2

p3: p3.awk
	clear
	gawk -f p3.awk < harrypotter2

p4: p4.awk
	clear
	gawk -f p4.awk < harrypotter2

clean:
	rm -f *.html
	rm -f -r html/
